#!/usr/bin/env bash

source $(dirname $(realpath $0))/../CUSTOM_INFO

# a docker image tag with the format 'name:tag'.
# generated by CUSTOM_INFO above.
# eg: alexlee/test-u:latest
IMGTAG=${USERNAME:-$(id -un)}/${IMGNAME:-"test-u"}:${VERSION:-"latest"}

docker build \
    --build-arg userid=$(id -u) \
    --build-arg groupid=$(id -g) \
    --build-arg username=$(id -un) \
    --build-arg packages="${PKGS}" \
    --label maintainer="${maintainer}" \
    -t ${IMGTAG} \
    $(dirname $(realpath $0))/..

docker image prune -f
